// day01/后台题目系统/web_demo/src/views/Login.vue
<template>
  <div class="login">
    <el-card>
      <el-form ref="loginForm" :model="loginForm" :rules="loginRules" label-width="80px">
        <el-form-item label="用户名" prop="username">
          <el-input v-model="loginForm.username"></el-input>
        </el-form-item>
        <el-form-item label="用户密码" prop="password">
          <el-input v-model="loginForm.password"></el-input>
        </el-form-item>
      </el-form>
      <el-button type="primary" @click="login">登录</el-button>
    </el-card>
  </div>
</template>

<script>
import querystring from 'querystring'
export default {
  data () {
    return {
      loginForm: {
        username: '',
        password: ''
      },
      loginRules: {
        username: [
          { required: true, message: '请输入用户名', trigger: 'blur' },
          { min: 3, max: 12, message: '长度在 3 到 12 个字符', trigger: 'blur' }
        ],
        password: [
          { required: true, message: '请输入用户密码', trigger: 'blur' },
          { min: 6, max: 18, message: '长度在 6 到 18 个字符', trigger: 'blur' }
        ]
      }
    }
  },
  methods: {
    async login () {
      let { data: res } = await this.$axios.post('/login', querystring.stringify(this.loginForm))
      // 如果用户名或密码错误 那么提示用户不存在
      // 如果用户名和密码正确 提示登录成功
      if (res.code !== 200) {
        window.sessionStorage.clear()
        return this.$message.error(res.msg)
      }
      // 令牌相当于古代调军队的虎符 就要存下来
      window.sessionStorage.setItem('token', res.data.token)
      window.sessionStorage.setItem('username', res.data.username)

      // 当登录成功 跳转到首页
      this.$router.push('/')
      // 登录成功提示
      return this.$message.success(res.msg)
    }
  }
}
</script>

<style>
.login {
  width: 600px;
  height: 500px;
  margin: 200px auto;
}
</style>

// dessert-react/src/Login.js
import React from 'react'

import { Form, Input, Button, Icon, message } from 'antd'

import Axios from 'axios'

function Login(props) {
  const { getFieldDecorator } = props.form;

  // 创建登录方法
  let seveLogin = () => {
    props.form.validateFields((err, values) => {
      if (!err) {
        Axios.post('/admin/login', values).then((res) => {
          if (res.data.code === 200) {
            message.success('登录成功！')
            localStorage.setItem('token', res.data.token)
            props.history.push('/')
          } else {
            message.error(res.data.error)
          }
        })
      }
    })
  }
  return (
    <div id='login'>
      < Form >
        <Form.Item hasFeedback >
          {
            getFieldDecorator('name', {
              rules: [
                {
                  required: true,
                  message: '必须填写管理员名称！'
                }
              ]
            })(
              <Input
                prefix={<Icon type="user" />}
                placeholder='请输入管理员名称'
              />
            )
          }
        </Form.Item>
        <Form.Item hasFeedback >
          {
            getFieldDecorator('password', {
              rules: [
                {
                  required: true,
                  message: '必须填写管理员密码！'
                }
              ]
            })(
              <Input
                prefix={<Icon type="user" />}
                placeholder='请输入管理员密码'
              />
            )
          }
        </Form.Item>
        <Form.Item>
          <Button  className='btn' type='primary' onClick={seveLogin}>
            登录
        </Button>
        </Form.Item>
      </Form >
    </div>
  )
}


const login = Form.create()(Login)

export default login
